# Generated by Django 6.0.2 on 2026-03-04 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Town, state or region', max_length=200)),
                ('farm_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('silt', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky'), ('unknown', 'I am not sure')], default='unknown', max_length=20)),
                ('ph_level', models.CharField(choices=[('acidic', 'Acidic  (tastes sour, kills grass)'), ('neutral', 'Neutral (normal soil)'), ('alkaline', 'Alkaline (white crust on soil surface)'), ('unknown', 'I am not sure')], default='unknown', max_length=20)),
                ('water_source', models.CharField(choices=[('rainfed', 'Rainfed only'), ('irrigated', 'I have irrigation'), ('seasonal', 'Seasonal stream / borehole')], default='rainfed', max_length=20)),
                ('current_crops', models.TextField(blank=True, help_text='Comma separated, e.g. maize, cassava')),
                ('past_crops', models.TextField(blank=True, help_text='What have you grown before?')),
                ('has_livestock', models.BooleanField(default=False)),
                ('livestock_types', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
