# Generated by Django 6.0.2 on 2026-03-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_farmerprofile_farm_size_acres'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('ig', 'Igbo'), ('yo', 'Yoruba')], default='en', max_length=5),
        ),
    ]
