# Generated by Django 6.0.2 on 2026-03-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_farmerprofile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
