# Generated by Django 6.0.2 on 2026-03-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_farmerprofile_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='top_pests',
            field=models.TextField(blank=True, help_text='Pests usually encountered (e.g. armyworms, aphids)'),
        ),
    ]
