# Generated by Django 6.0.2 on 2026-03-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_farmerprofile_top_pests'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='security_answer',
            field=models.CharField(blank=True, help_text="Answer to security question (grandfather's name)", max_length=200),
        ),
    ]
