# Generated by Django 6.0.3 on 2026-03-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_farmerprofile_security_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Town, state or region', max_length=200, null=True),
        ),
    ]
