# Generated by Django 6.0.2 on 2026-03-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_farmerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ha', 'Hausa'), ('ig', 'Igbo'), ('yo', 'Yoruba'), ('pcm', 'Pidgin')], default='en', max_length=5),
        ),
    ]
