# Generated by Django 6.0.2 on 2026-03-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_farmerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
