# Generated by Django 6.0.2 on 2026-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
